### ISSUE TITLE
Alias support

### ISSUE THREAD

**Issue by SteveZuercher** [jvalenzuela/l5x#3]
I have a need to change alias tags. Can something like ".alias" be added to the tag element? I'd like the ability to reference global scope and program scope. something like:
prj.controller.tags['global tag'].alias = prj.controller.tags['a different global tag'].name
OR
prj.programs['MainProgram'].tags['a_program_tag'].alias = prj.controller.tags['global tag'].name
prj.programs['MainProgram'].tags['a_program_tag'].alias = prj.programs['MainProgram'].tags['a_different_program_tag'].name

This would reference the "AliasFor" attribute. I would hope it checks the tag has the attribute TagType="Alias".

**Comment by jvalenzuela** [comment]
Implemented in 260fa9e and 1156f56.
