### ISSUE TITLE
Adding Tags

### ISSUE THREAD

**Issue by JazzGlobal** [jvalenzuela/l5x#7]
Are you able to add tags to the code by using this lib?

**Comment by jvalenzuela** [comment]
No. It can be used to resize existing arrays, but it cannot create new tags.


Jason Valenzuela

**Comment by JazzGlobal** [comment]
Thanks!

**Comment by aliksimon** [comment]
I was just wondering the same.
For changing a tag into an alias_tag I was able to change the underlying `element`:
`project.controller.tags[tag_alias_name].element.set('TagType', 'Alias')`

Do you see some (maybe similar) way to add new tags or new AOIs or new UDTs?

Do you expect it to be feasible to include this in this project, i.e. is it a good idea if your or I try to implement it?
